// <auto-generated />
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace UltraFrameAI.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[CompilerGenerated]
public static class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    public static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                resourceMan = new ResourceManager("UltraFrameAI.Resources.Strings", typeof(Strings).Assembly);
            }

            return resourceMan;
        }
    }

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string AppTitle => GetRequired(nameof(AppTitle));
    public static string Subtitle => GetRequired(nameof(Subtitle));
    public static string Workspace => GetRequired(nameof(Workspace));
    public static string DropZoneTitle => GetRequired(nameof(DropZoneTitle));
    public static string DropZoneHelp => GetRequired(nameof(DropZoneHelp));
    public static string RootFolder => GetRequired(nameof(RootFolder));
    public static string Browse => GetRequired(nameof(Browse));
    public static string BrowseFolder => GetRequired(nameof(BrowseFolder));
    public static string BrowseFile => GetRequired(nameof(BrowseFile));
    public static string BrowseVideoFileDialogTitle => GetRequired(nameof(BrowseVideoFileDialogTitle));
    public static string ResetToLastFolder => GetRequired(nameof(ResetToLastFolder));
    public static string RecentFolders => GetRequired(nameof(RecentFolders));
    public static string OutputFolder => GetRequired(nameof(OutputFolder));
    public static string OutputFolderLabel => GetRequired(nameof(OutputFolderLabel));
    public static string Advanced => GetRequired(nameof(Advanced));
    public static string Benchmark => GetRequired(nameof(Benchmark));
    public static string BenchmarkHint => GetRequired(nameof(BenchmarkHint));
    public static string BenchmarkWindowTitle => GetRequired(nameof(BenchmarkWindowTitle));
    public static string BenchmarkChartsWindowTitle => GetRequired(nameof(BenchmarkChartsWindowTitle));
    public static string BenchmarkChartsHint => GetRequired(nameof(BenchmarkChartsHint));
    public static string BenchmarkChartsWindowHint => GetRequired(nameof(BenchmarkChartsWindowHint));
    public static string BenchmarkChartsOpen => GetRequired(nameof(BenchmarkChartsOpen));
    public static string BenchmarkSourceLabel => GetRequired(nameof(BenchmarkSourceLabel));
    public static string BenchmarkSourceHint => GetRequired(nameof(BenchmarkSourceHint));
    public static string BenchmarkSourceFileLabel => GetRequired(nameof(BenchmarkSourceFileLabel));
    public static string BenchmarkSourceFileHint => GetRequired(nameof(BenchmarkSourceFileHint));
    public static string BenchmarkOutputLabel => GetRequired(nameof(BenchmarkOutputLabel));
    public static string BenchmarkOutputHint => GetRequired(nameof(BenchmarkOutputHint));
    public static string BenchmarkChooseSourceFileFirst => GetRequired(nameof(BenchmarkChooseSourceFileFirst));
    public static string BenchmarkSampleSeconds => GetRequired(nameof(BenchmarkSampleSeconds));
    public static string BenchmarkQualityNote => GetRequired(nameof(BenchmarkQualityNote));
    public static string BenchmarkWinnerTitle => GetRequired(nameof(BenchmarkWinnerTitle));
    public static string BenchmarkFastestOverallLabel => GetRequired(nameof(BenchmarkFastestOverallLabel));
    public static string BenchmarkWeightedRecommendationLabel => GetRequired(nameof(BenchmarkWeightedRecommendationLabel));
    public static string BenchmarkBestQualityTimeLabel => GetRequired(nameof(BenchmarkBestQualityTimeLabel));
    public static string BenchmarkRuntimeMode => GetRequired(nameof(BenchmarkRuntimeMode));
    public static string BenchmarkQualityTimeMode => GetRequired(nameof(BenchmarkQualityTimeMode));
    public static string BenchmarkCurrentStep => GetRequired(nameof(BenchmarkCurrentStep));
    public static string BenchmarkCurrentCase => GetRequired(nameof(BenchmarkCurrentCase));
    public static string BenchmarkScatterTitle => GetRequired(nameof(BenchmarkScatterTitle));
    public static string BenchmarkHistogramTitle => GetRequired(nameof(BenchmarkHistogramTitle));
    public static string BenchmarkSortLabel => GetRequired(nameof(BenchmarkSortLabel));
    public static string BenchmarkSortMetric => GetRequired(nameof(BenchmarkSortMetric));
    public static string BenchmarkSortName => GetRequired(nameof(BenchmarkSortName));
    public static string BenchmarkLegendCodecPreset => GetRequired(nameof(BenchmarkLegendCodecPreset));
    public static string BenchmarkLegendAntiFlicker => GetRequired(nameof(BenchmarkLegendAntiFlicker));
    public static string BenchmarkLegendThreads => GetRequired(nameof(BenchmarkLegendThreads));
    public static string BenchmarkLegendTileSize => GetRequired(nameof(BenchmarkLegendTileSize));
    public static string BenchmarkLegendFastest => GetRequired(nameof(BenchmarkLegendFastest));
    public static string BenchmarkLegendBestQualityTime => GetRequired(nameof(BenchmarkLegendBestQualityTime));
    public static string LastRunSummaryTitle => GetRequired(nameof(LastRunSummaryTitle));
    public static string LastRunSummaryFormat => GetRequired(nameof(LastRunSummaryFormat));
    public static string BenchmarkLogSource => GetRequired(nameof(BenchmarkLogSource));
    public static string BenchmarkLogSample => GetRequired(nameof(BenchmarkLogSample));
    public static string BenchmarkLogSampleStart => GetRequired(nameof(BenchmarkLogSampleStart));
    public static string BenchmarkLogSampleDuration => GetRequired(nameof(BenchmarkLogSampleDuration));
    public static string BenchmarkLogGroupSection => GetRequired(nameof(BenchmarkLogGroupSection));
    public static string BenchmarkLogSummary => GetRequired(nameof(BenchmarkLogSummary));
    public static string BenchmarkLogFastestOverall => GetRequired(nameof(BenchmarkLogFastestOverall));
    public static string BenchmarkLogBestCodecPreset => GetRequired(nameof(BenchmarkLogBestCodecPreset));
    public static string BenchmarkLogBestAntiFlicker => GetRequired(nameof(BenchmarkLogBestAntiFlicker));
    public static string BenchmarkLogBestUpscalerThreads => GetRequired(nameof(BenchmarkLogBestUpscalerThreads));
    public static string BenchmarkLogBestTileSize => GetRequired(nameof(BenchmarkLogBestTileSize));
    public static string BenchmarkLogBestSettings => GetRequired(nameof(BenchmarkLogBestSettings));
    public static string BenchmarkLogRecommendedFastPreset => GetRequired(nameof(BenchmarkLogRecommendedFastPreset));
    public static string BenchmarkLogMetricsSummary => GetRequired(nameof(BenchmarkLogMetricsSummary));
    public static string BenchmarkSummaryRecommendedFastPreset => GetRequired(nameof(BenchmarkSummaryRecommendedFastPreset));
    public static string BenchmarkSummaryBestSettings => GetRequired(nameof(BenchmarkSummaryBestSettings));
    public static string BenchmarkSummaryMetricsSummary => GetRequired(nameof(BenchmarkSummaryMetricsSummary));
    public static string BenchmarkReportTableGroup => GetRequired(nameof(BenchmarkReportTableGroup));
    public static string BenchmarkReportTableCase => GetRequired(nameof(BenchmarkReportTableCase));
    public static string BenchmarkReportTableCodec => GetRequired(nameof(BenchmarkReportTableCodec));
    public static string BenchmarkReportTablePreset => GetRequired(nameof(BenchmarkReportTablePreset));
    public static string BenchmarkReportTableAf => GetRequired(nameof(BenchmarkReportTableAf));
    public static string BenchmarkReportTableMode => GetRequired(nameof(BenchmarkReportTableMode));
    public static string BenchmarkReportTableStrength => GetRequired(nameof(BenchmarkReportTableStrength));
    public static string BenchmarkReportTableThreads => GetRequired(nameof(BenchmarkReportTableThreads));
    public static string BenchmarkReportTableTile => GetRequired(nameof(BenchmarkReportTableTile));
    public static string BenchmarkReportTableTime => GetRequired(nameof(BenchmarkReportTableTime));
    public static string BenchmarkReportTableOutputMb => GetRequired(nameof(BenchmarkReportTableOutputMb));
    public static string BenchmarkReportTableCpu => GetRequired(nameof(BenchmarkReportTableCpu));
    public static string BenchmarkReportTableRamGb => GetRequired(nameof(BenchmarkReportTableRamGb));
    public static string BenchmarkReportTableGpu => GetRequired(nameof(BenchmarkReportTableGpu));
    public static string BenchmarkReportTableVramGb => GetRequired(nameof(BenchmarkReportTableVramGb));
    public static string BenchmarkCaseCodecPreset => GetRequired(nameof(BenchmarkCaseCodecPreset));
    public static string BenchmarkCaseAntiFlickerOff => GetRequired(nameof(BenchmarkCaseAntiFlickerOff));
    public static string BenchmarkCaseAntiFlickerVideo => GetRequired(nameof(BenchmarkCaseAntiFlickerVideo));
    public static string BenchmarkCaseAntiFlickerFaces => GetRequired(nameof(BenchmarkCaseAntiFlickerFaces));
    public static string BenchmarkCaseAntiFlickerAnime => GetRequired(nameof(BenchmarkCaseAntiFlickerAnime));
    public static string BenchmarkCaseAntiFlickerAnimeUltra => GetRequired(nameof(BenchmarkCaseAntiFlickerAnimeUltra));
    public static string BenchmarkVideoFilesFilter => GetRequired(nameof(BenchmarkVideoFilesFilter));
    public static string BenchmarkErrorRequiresSource => GetRequired(nameof(BenchmarkErrorRequiresSource));
    public static string BenchmarkErrorNoVideoFilesFound => GetRequired(nameof(BenchmarkErrorNoVideoFilesFound));
    public static string BenchmarkErrorSourceFileNotFound => GetRequired(nameof(BenchmarkErrorSourceFileNotFound));
    public static string BenchmarkErrorUnableToCreateSampleClipWithExitCode => GetRequired(nameof(BenchmarkErrorUnableToCreateSampleClipWithExitCode));
    public static string BenchmarkErrorUnableToCreateSampleClip => GetRequired(nameof(BenchmarkErrorUnableToCreateSampleClip));
    public static string BenchmarkErrorPipelineFailed => GetRequired(nameof(BenchmarkErrorPipelineFailed));
    public static string BenchmarkShortCodecFast => GetRequired(nameof(BenchmarkShortCodecFast));
    public static string BenchmarkSuccess => GetRequired(nameof(BenchmarkSuccess));
    public static string BenchmarkFailure => GetRequired(nameof(BenchmarkFailure));
    public static string BenchmarkNotAvailable => GetRequired(nameof(BenchmarkNotAvailable));
    public static string BenchmarkStatusStarting => GetRequired(nameof(BenchmarkStatusStarting));
    public static string BenchmarkStatusStarted => GetRequired(nameof(BenchmarkStatusStarted));
    public static string BenchmarkStatusFinished => GetRequired(nameof(BenchmarkStatusFinished));
    public static string BenchmarkStatusCancelled => GetRequired(nameof(BenchmarkStatusCancelled));
    public static string BenchmarkStatusCancelledUser => GetRequired(nameof(BenchmarkStatusCancelledUser));
    public static string BenchmarkStatusFailed => GetRequired(nameof(BenchmarkStatusFailed));
    public static string BenchmarkStatusStartingDetailed => GetRequired(nameof(BenchmarkStatusStartingDetailed));
    public static string BenchmarkCaseStarted => GetRequired(nameof(BenchmarkCaseStarted));
    public static string BenchmarkCaseCompleted => GetRequired(nameof(BenchmarkCaseCompleted));
    public static string BenchmarkSummaryHeader => GetRequired(nameof(BenchmarkSummaryHeader));
    public static string BenchmarkSummaryFastestOverall => GetRequired(nameof(BenchmarkSummaryFastestOverall));
    public static string BenchmarkSummaryBestCodecPreset => GetRequired(nameof(BenchmarkSummaryBestCodecPreset));
    public static string BenchmarkSummaryBestAntiFlicker => GetRequired(nameof(BenchmarkSummaryBestAntiFlicker));
    public static string BenchmarkSummaryBestUpscalerThreads => GetRequired(nameof(BenchmarkSummaryBestUpscalerThreads));
    public static string BenchmarkSummaryBestTileSize => GetRequired(nameof(BenchmarkSummaryBestTileSize));
    public static string BenchmarkShortCodecMed => GetRequired(nameof(BenchmarkShortCodecMed));
    public static string BenchmarkShortCodecSlow => GetRequired(nameof(BenchmarkShortCodecSlow));
    public static string BenchmarkShortCodecVFast => GetRequired(nameof(BenchmarkShortCodecVFast));
    public static string BenchmarkShortAFOff => GetRequired(nameof(BenchmarkShortAFOff));
    public static string BenchmarkShortAFOn => GetRequired(nameof(BenchmarkShortAFOn));
    public static string BenchmarkShortAFAnime => GetRequired(nameof(BenchmarkShortAFAnime));
    public static string BenchmarkShortAFUltra => GetRequired(nameof(BenchmarkShortAFUltra));
    public static string BenchmarkShortAFVideo => GetRequired(nameof(BenchmarkShortAFVideo));
    public static string BenchmarkShortAFFaces => GetRequired(nameof(BenchmarkShortAFFaces));
    public static string BenchmarkShortThreadsPrefix => GetRequired(nameof(BenchmarkShortThreadsPrefix));
    public static string BenchmarkShortTilePrefix => GetRequired(nameof(BenchmarkShortTilePrefix));
    public static string BenchmarkNoResults => GetRequired(nameof(BenchmarkNoResults));
    public static string BenchmarkChartTimeAxis => GetRequired(nameof(BenchmarkChartTimeAxis));
    public static string BenchmarkChartQualityAxis => GetRequired(nameof(BenchmarkChartQualityAxis));
    public static string BenchmarkStart => GetRequired(nameof(BenchmarkStart));
    public static string BenchmarkStop => GetRequired(nameof(BenchmarkStop));
    public static string AntiFlicker => GetRequired(nameof(AntiFlicker));
    public static string AntiFlickerHint => GetRequired(nameof(AntiFlickerHint));
    public static string AntiFlickerStrength => GetRequired(nameof(AntiFlickerStrength));
    public static string AntiFlickerPreset => GetRequired(nameof(AntiFlickerPreset));
    public static string AntiFlickerPresetHint => GetRequired(nameof(AntiFlickerPresetHint));
    public static string AntiFlickerAnimeHint => GetRequired(nameof(AntiFlickerAnimeHint));
    public static string AntiFlickerVideoHint => GetRequired(nameof(AntiFlickerVideoHint));
    public static string AntiFlickerFacesHint => GetRequired(nameof(AntiFlickerFacesHint));
    public static string AntiFlickerUltra => GetRequired(nameof(AntiFlickerUltra));
    public static string AntiFlickerUltraHint => GetRequired(nameof(AntiFlickerUltraHint));
    public static string ContentMode => GetRequired(nameof(ContentMode));
    public static string ContentModeAnime => GetRequired(nameof(ContentModeAnime));
    public static string ContentModeAnimeUltra => GetRequired(nameof(ContentModeAnimeUltra));
    public static string ContentModeVideo => GetRequired(nameof(ContentModeVideo));
    public static string ContentModeFaces => GetRequired(nameof(ContentModeFaces));
    public static string QuickStartHint => GetRequired(nameof(QuickStartHint));
    public static string ScanningFolder => GetRequired(nameof(ScanningFolder));
    public static string Phase => GetRequired(nameof(Phase));
    public static string ScanFolderProgress => GetRequired(nameof(ScanFolderProgress));
    public static string SelectVideoFolder => GetRequired(nameof(SelectVideoFolder));
    public static string SelectOutputFolder => GetRequired(nameof(SelectOutputFolder));
    public static string Codec => GetRequired(nameof(Codec));
    public static string Target => GetRequired(nameof(Target));
    public static string Resolution => GetRequired(nameof(Resolution));
    public static string Container => GetRequired(nameof(Container));
    public static string FFmpegThreads => GetRequired(nameof(FFmpegThreads));
    public static string UpscalerJobs => GetRequired(nameof(UpscalerJobs));
    public static string TileSize => GetRequired(nameof(TileSize));
    public static string OverwriteExistingOutput => GetRequired(nameof(OverwriteExistingOutput));
    public static string ScanFiles => GetRequired(nameof(ScanFiles));
    public static string StartBatch => GetRequired(nameof(StartBatch));
    public static string StartSelected => GetRequired(nameof(StartSelected));
    public static string CancelJob => GetRequired(nameof(CancelJob));
    public static string OpenOutputFolder => GetRequired(nameof(OpenOutputFolder));
    public static string CloseDuringRenderTitle => GetRequired(nameof(CloseDuringRenderTitle));
    public static string CloseDuringRenderMessage => GetRequired(nameof(CloseDuringRenderMessage));
    public static string CloseDuringRenderStop => GetRequired(nameof(CloseDuringRenderStop));
    public static string CloseDuringRenderKeep => GetRequired(nameof(CloseDuringRenderKeep));
    public static string DeleteItem => GetRequired(nameof(DeleteItem));
    public static string DeleteSelected => GetRequired(nameof(DeleteSelected));
    public static string DeleteAll => GetRequired(nameof(DeleteAll));
    public static string DeleteAllConfirmTitle => GetRequired(nameof(DeleteAllConfirmTitle));
    public static string DeleteAllConfirmMessage => GetRequired(nameof(DeleteAllConfirmMessage));
    public static string CurrentStage => GetRequired(nameof(CurrentStage));
    public static string Elapsed => GetRequired(nameof(Elapsed));
    public static string ETA => GetRequired(nameof(ETA));
    public static string ProgressDetails => GetRequired(nameof(ProgressDetails));
    public static string StepDuration => GetRequired(nameof(StepDuration));
    public static string Queue => GetRequired(nameof(Queue));
    public static string Log => GetRequired(nameof(Log));
    public static string LogTime => GetRequired(nameof(LogTime));
    public static string LogMessage => GetRequired(nameof(LogMessage));
    public static string LogInvalidVideoInfo => GetRequired(nameof(LogInvalidVideoInfo));
    public static string NoItemSelected => GetRequired(nameof(NoItemSelected));
    public static string PickFolderHint => GetRequired(nameof(PickFolderHint));
    public static string WaitingForInput => GetRequired(nameof(WaitingForInput));
    public static string Ready => GetRequired(nameof(Ready));
    public static string Idle => GetRequired(nameof(Idle));
    public static string Cancelled => GetRequired(nameof(Cancelled));
    public static string ScanningFiles => GetRequired(nameof(ScanningFiles));
    public static string FoundVideoFiles => GetRequired(nameof(FoundVideoFiles));
    public static string ItemCount => GetRequired(nameof(ItemCount));
    public static string StartingBatch => GetRequired(nameof(StartingBatch));
    public static string BatchFinished => GetRequired(nameof(BatchFinished));
    public static string LogStartingSelectedBatch => GetRequired(nameof(LogStartingSelectedBatch));
    public static string BatchFailed => GetRequired(nameof(BatchFailed));
    public static string ScanFailed => GetRequired(nameof(ScanFailed));
    public static string RootNotFound => GetRequired(nameof(RootNotFound));
    public static string ScanCurrentFolder => GetRequired(nameof(ScanCurrentFolder));
    public static string ScanCurrentFile => GetRequired(nameof(ScanCurrentFile));
    public static string ScanFoundVideos => GetRequired(nameof(ScanFoundVideos));
    public static string UnableToResolveTimestamps => GetRequired(nameof(UnableToResolveTimestamps));
    public static string UnableToBuildTimeline => GetRequired(nameof(UnableToBuildTimeline));
    public static string NoFramesExtracted => GetRequired(nameof(NoFramesExtracted));
    public static string NoItemsFound => GetRequired(nameof(NoItemsFound));
    public static string Preparing => GetRequired(nameof(Preparing));
    public static string LogProcessing => GetRequired(nameof(LogProcessing));
    public static string OutputExists => GetRequired(nameof(OutputExists));
    public static string SkippingEncode => GetRequired(nameof(SkippingEncode));
    public static string OldSrcMovedAside => GetRequired(nameof(OldSrcMovedAside));
    public static string OldUpMovedAside => GetRequired(nameof(OldUpMovedAside));
    public static string ExtractingFrames => GetRequired(nameof(ExtractingFrames));
    public static string UpscalingFrames => GetRequired(nameof(UpscalingFrames));
    public static string EncodingVideo => GetRequired(nameof(EncodingVideo));
    public static string ItemComplete => GetRequired(nameof(ItemComplete));
    public static string ExtractionComplete => GetRequired(nameof(ExtractionComplete));
    public static string UpscaleComplete => GetRequired(nameof(UpscaleComplete));
    public static string EncodeComplete => GetRequired(nameof(EncodeComplete));
    public static string BatchComplete => GetRequired(nameof(BatchComplete));
    public static string StartingItem => GetRequired(nameof(StartingItem));
    public static string FinishedItem => GetRequired(nameof(FinishedItem));
    public static string ExtractedFrames => GetRequired(nameof(ExtractedFrames));
    public static string UpscaledFrames => GetRequired(nameof(UpscaledFrames));
    public static string WroteFile => GetRequired(nameof(WroteFile));
    public static string ItemSummary => GetRequired(nameof(ItemSummary));
    public static string Language => GetRequired(nameof(Language));
    public static string LanguageEnglish => GetRequired(nameof(LanguageEnglish));
    public static string LanguageRussian => GetRequired(nameof(LanguageRussian));
    public static string LanguageGerman => GetRequired(nameof(LanguageGerman));
    public static string QueueIndex => GetRequired(nameof(QueueIndex));
    public static string QueueItem => GetRequired(nameof(QueueItem));
    public static string QueueStage => GetRequired(nameof(QueueStage));
    public static string QueueProgress => GetRequired(nameof(QueueProgress));
    public static string QueueElapsed => GetRequired(nameof(QueueElapsed));
    public static string QueueETA => GetRequired(nameof(QueueETA));
    public static string QueueOutput => GetRequired(nameof(QueueOutput));
    public static string QueueStatus => GetRequired(nameof(QueueStatus));
    public static string QueueStatusNew => GetRequired(nameof(QueueStatusNew));
    public static string QueueStatusCompleted => GetRequired(nameof(QueueStatusCompleted));
    private static string GetRequired(string key)
    {
        return ResourceManager.GetString(key, resourceCulture) ?? throw new MissingManifestResourceException($"Missing resource: {key}");
    }
}
