// <auto-generated />
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace UltraFrameAI.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[CompilerGenerated]
public static class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    public static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                resourceMan = new ResourceManager("UltraFrameAI.Resources.Strings", typeof(Strings).Assembly);
            }

            return resourceMan;
        }
    }

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string AppTitle => GetRequired(nameof(AppTitle));
    public static string Subtitle => GetRequired(nameof(Subtitle));
    public static string Workspace => GetRequired(nameof(Workspace));
    public static string DropZoneTitle => GetRequired(nameof(DropZoneTitle));
    public static string DropZoneHelp => GetRequired(nameof(DropZoneHelp));
    public static string RootFolder => GetRequired(nameof(RootFolder));
    public static string Browse => GetRequired(nameof(Browse));
    public static string ResetToLastFolder => GetRequired(nameof(ResetToLastFolder));
    public static string RecentFolders => GetRequired(nameof(RecentFolders));
    public static string OutputFolder => GetRequired(nameof(OutputFolder));
    public static string Advanced => GetRequired(nameof(Advanced));
    public static string QuickStartHint => GetRequired(nameof(QuickStartHint));
    public static string ScanningFolder => GetRequired(nameof(ScanningFolder));
    public static string Phase => GetRequired(nameof(Phase));
    public static string ScanFolderProgress => GetRequired(nameof(ScanFolderProgress));
    public static string SelectVideoFolder => GetRequired(nameof(SelectVideoFolder));
    public static string SelectOutputFolder => GetRequired(nameof(SelectOutputFolder));
    public static string Codec => GetRequired(nameof(Codec));
    public static string Target => GetRequired(nameof(Target));
    public static string FFmpegThreads => GetRequired(nameof(FFmpegThreads));
    public static string UpscalerJobs => GetRequired(nameof(UpscalerJobs));
    public static string TileSize => GetRequired(nameof(TileSize));
    public static string OverwriteExistingOutput => GetRequired(nameof(OverwriteExistingOutput));
    public static string KeepTempFolders => GetRequired(nameof(KeepTempFolders));
    public static string ScanFiles => GetRequired(nameof(ScanFiles));
    public static string StartBatch => GetRequired(nameof(StartBatch));
    public static string CancelJob => GetRequired(nameof(CancelJob));
    public static string OpenOutputFolder => GetRequired(nameof(OpenOutputFolder));
    public static string DeleteItem => GetRequired(nameof(DeleteItem));
    public static string DeleteSelected => GetRequired(nameof(DeleteSelected));
    public static string DeleteAll => GetRequired(nameof(DeleteAll));
    public static string DeleteAllConfirmTitle => GetRequired(nameof(DeleteAllConfirmTitle));
    public static string DeleteAllConfirmMessage => GetRequired(nameof(DeleteAllConfirmMessage));
    public static string CurrentStage => GetRequired(nameof(CurrentStage));
    public static string Elapsed => GetRequired(nameof(Elapsed));
    public static string ETA => GetRequired(nameof(ETA));
    public static string ProgressDetails => GetRequired(nameof(ProgressDetails));
    public static string StepDuration => GetRequired(nameof(StepDuration));
    public static string Queue => GetRequired(nameof(Queue));
    public static string Log => GetRequired(nameof(Log));
    public static string NoItemSelected => GetRequired(nameof(NoItemSelected));
    public static string PickFolderHint => GetRequired(nameof(PickFolderHint));
    public static string WaitingForInput => GetRequired(nameof(WaitingForInput));
    public static string Ready => GetRequired(nameof(Ready));
    public static string Idle => GetRequired(nameof(Idle));
    public static string Cancelled => GetRequired(nameof(Cancelled));
    public static string ScanningFiles => GetRequired(nameof(ScanningFiles));
    public static string FoundVideoFiles => GetRequired(nameof(FoundVideoFiles));
    public static string ItemCount => GetRequired(nameof(ItemCount));
    public static string StartingBatch => GetRequired(nameof(StartingBatch));
    public static string BatchFinished => GetRequired(nameof(BatchFinished));
    public static string BatchFailed => GetRequired(nameof(BatchFailed));
    public static string ScanFailed => GetRequired(nameof(ScanFailed));
    public static string RootNotFound => GetRequired(nameof(RootNotFound));
    public static string ScanCurrentFolder => GetRequired(nameof(ScanCurrentFolder));
    public static string ScanCurrentFile => GetRequired(nameof(ScanCurrentFile));
    public static string ScanFoundVideos => GetRequired(nameof(ScanFoundVideos));
    public static string UnableToResolveTimestamps => GetRequired(nameof(UnableToResolveTimestamps));
    public static string UnableToBuildTimeline => GetRequired(nameof(UnableToBuildTimeline));
    public static string NoFramesExtracted => GetRequired(nameof(NoFramesExtracted));
    public static string NoItemsFound => GetRequired(nameof(NoItemsFound));
    public static string Preparing => GetRequired(nameof(Preparing));
    public static string LogProcessing => GetRequired(nameof(LogProcessing));
    public static string OutputExists => GetRequired(nameof(OutputExists));
    public static string SkippingEncode => GetRequired(nameof(SkippingEncode));
    public static string OldSrcMovedAside => GetRequired(nameof(OldSrcMovedAside));
    public static string OldUpMovedAside => GetRequired(nameof(OldUpMovedAside));
    public static string ExtractingFrames => GetRequired(nameof(ExtractingFrames));
    public static string UpscalingFrames => GetRequired(nameof(UpscalingFrames));
    public static string EncodingVideo => GetRequired(nameof(EncodingVideo));
    public static string ItemComplete => GetRequired(nameof(ItemComplete));
    public static string ExtractionComplete => GetRequired(nameof(ExtractionComplete));
    public static string UpscaleComplete => GetRequired(nameof(UpscaleComplete));
    public static string EncodeComplete => GetRequired(nameof(EncodeComplete));
    public static string BatchComplete => GetRequired(nameof(BatchComplete));
    public static string StartingItem => GetRequired(nameof(StartingItem));
    public static string FinishedItem => GetRequired(nameof(FinishedItem));
    public static string ExtractedFrames => GetRequired(nameof(ExtractedFrames));
    public static string UpscaledFrames => GetRequired(nameof(UpscaledFrames));
    public static string WroteFile => GetRequired(nameof(WroteFile));
    public static string ItemSummary => GetRequired(nameof(ItemSummary));
    public static string Language => GetRequired(nameof(Language));
    public static string LanguageEnglish => GetRequired(nameof(LanguageEnglish));
    public static string LanguageRussian => GetRequired(nameof(LanguageRussian));
    public static string LanguageGerman => GetRequired(nameof(LanguageGerman));
    public static string QueueIndex => GetRequired(nameof(QueueIndex));
    public static string QueueItem => GetRequired(nameof(QueueItem));
    public static string QueueStage => GetRequired(nameof(QueueStage));
    public static string QueueProgress => GetRequired(nameof(QueueProgress));
    public static string QueueElapsed => GetRequired(nameof(QueueElapsed));
    public static string QueueETA => GetRequired(nameof(QueueETA));
    public static string QueueOutput => GetRequired(nameof(QueueOutput));
    private static string GetRequired(string key)
    {
        return ResourceManager.GetString(key, resourceCulture) ?? throw new MissingManifestResourceException($"Missing resource: {key}");
    }
}
